[package]
name = "lgtm-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "egui-based GUI for lgtm."

[dependencies]
lgtm-core.workspace = true
eframe.workspace = true
egui.workspace = true
anyhow.workspace = true
tracing.workspace = true
chrono.workspace = true
rfd.workspace = true
